### ISSUE TITLE
Tags Indentation option doesn't open to another menu.

### ISSUE THREAD

**Issue by keithcrone** [orgzly/orgzly-android#201] opened 2017-10-26 18:01 UTC
It doesn't crash. It just displays a blank screen. Pressing back just goes back to normal Settings menu.

**Comment by nevenz** [comment] 2017-10-26 18:45
> It doesn't crash. It just displays a blank screen. Pressing back just goes back to normal Settings menu.

Hmm weird... What about auto-sync's screen? Does it open normally?

Which device and Android version is this?

**Comment by keithcrone** [comment] 2017-10-26 18:48
Auto-sync menu seems ok. I wasn't going to try playing with it for a while but the menu seems to open ok.

Note 4, Android 6.0.1

**Comment by nevenz** [comment] 2017-10-26 19:05
> Auto-sync menu seems ok

Well that's even stranger. I can't reproduce it, but I'll see to change the way those are opened for beta.2. Thanks for reporting it.

Settings will re-written in one of the next versions. They should be in a separate activity and better organized (top-level headings only etc.).

**Comment by nevenz** [comment] 2017-10-26 19:27
> I can't reproduce it

Scratch that, I haven't tried it with generated APK. It will be fixed for next beta. Thanks again.

**Closed** 2017-10-28 14:19 UTC
Labels: type/bug
