### ISSUE TITLE
Automatic synchronization

### ISSUE THREAD

**Issue by vegai** [orgzly/orgzly-android#36] opened 2017-03-09 08:59 UTC
Problem: I often wind up in a situation where my phone's and Dropbox's org files are out of sync. What could remedy this a lot would be a combination of

 - automatically pulling from Dropbox (or whatever repo is configured) every, say, hour
 - automatically pushing changes to Dropbox (or whatever repo is configured) whenever I add anything on the phone

Both could be configurable options, of course.

**Comment by nevenz** [comment] 2017-03-09 23:14
Duplicate of #8.

**Closed by nevenz** 2017-03-09 23:14 UTC
Labels: duplicate
