### ISSUE TITLE
What is indented empty space in front of all subject item in Settings?

### ISSUE THREAD

**Issue by NiceFeather** [orgzly/orgzly-android#505] opened 2019-03-19 14:00 UTC
This maybe a question.
In latest Settings, I found there is indented empty space in front of all subject item in every category, What's it gonna be for?

![102621](https://user-images.githubusercontent.com/28109556/54611589-3700f100-4a92-11e9-9ffb-ab1be97d772d.jpg)

**Comment by nevenz** [comment] 2019-03-19 14:36
Nothing, padding is by design and it can't be removed easily without some workarounds, so I didn't bother. See https://issuetracker.google.com/issues/116170936.

**Comment by NiceFeather** [comment] 2019-03-21 05:28
So sorry I had never before had Android development. Looking into Google Issues Tracker, this bug seem has been fixed but not released by Google, but there should have some workarounds like [this one](https://issuetracker.google.com/issues/111907042#comment1) , also you can take reference to the issue [comment](https://issuetracker.google.com/issues/111907042#comment6) by Google staff. of course I think that tiling with icons or leaving this issue would be no problem..

So, as a system issue, you can close this, also leave it as bug.

**Comment by nevenz** [comment] 2019-03-25 08:19
I would have removed the padding, but I didn't want to use any workarounds.

Still, there could be some icons added in the future, as number of settings increase, so I'm going to close it.

**Closed by nevenz** 2019-03-25 08:19 UTC
