### ISSUE TITLE
Date/time selector for events

### ISSUE THREAD

**Issue by 0815horsti** [orgzly/orgzly-android#493] opened 2019-03-15 09:16 UTC
The new version introduced the reminder for events.

Is it possible to add some date/time picker in the title or the content of the note? Something like the selector used for the deadline or the scheduled time.

This would be much easier than adding all the information manually by the standard android keyboard ...

**Comment by nevenz** [comment] 2019-03-15 09:29
Yes, I think that's #108?

**Comment by 0815horsti** [comment] 2019-03-15 09:39
Not really.
I am thinking of an add-on to #76.

Azzamsa mentioned that you have to type it manually in the meantime ( I wasn't regisitered to GitHub yersterday).

**Comment by nevenz** [comment] 2019-03-25 06:44
Toolbar above keyboard with a button for opening selector and inserting time at cursor is what I was thinking in https://github.com/orgzly/orgzly-android/issues/108#issuecomment-309392807.

**Comment by memeplex** [comment] 2019-04-12 15:15
I always thought about the toolbar as a nice to have, but since the introduction of events its need become more pressing. It's hard to enter a complete, correct timestamp using the phone keyboard.

What about introducing the toolbar now, as a complement to event timestamps, even if this means it will be mostly empty for now?

**Comment by nevenz** [comment] 2019-09-27 17:24
Closing as a duplicate of #108.

**Closed by nevenz** 2019-09-27 17:24 UTC
Labels: New, Type: feature
