### ISSUE TITLE
Trailing New Line Added While Syncing to Dropbox

### ISSUE THREAD

**Issue by haimivan** [orgzly/orgzly-android#264] opened 2018-01-06 05:38 UTC
Hi,

I use Orgzly on an Android Smartphone and a Ubuntu Dropbox file system.

My Dropbox file looks like:
```
* note 1
text
=======
* note 2
```
I sync this to my smartphone, do a change on the smartphone and sync it back to the dropbox.

Result:
```
* note 1

text
=======

* note 2
```

Is it possible to suppress the new lines that occur after syncing back to Dropbox?

**Comment by nevenz** [comment] 2018-01-06 13:04
Yes, it's not Dropbox-specific - see Settings / Org file format / Separate notes with an empty line.

**Comment by haimivan** [comment] 2018-01-06 13:21
Thanks.

So if I set 
Settings / Org file format / Separate notes with an empty line = NEVER
Settings / Org file format / Separate header and content = OFF
it should leave in my case the file in the dropbox untouched, right?

**Comment by nevenz** [comment] 2018-01-06 14:26
Not untouched - if you had notes separated with blank line, that line would be removed.

See #190.

**Comment by haimivan** [comment] 2018-01-06 21:15
and is there any possibility to leave my original file untouched when syncing back to Dropbox?

**Comment by nevenz** [comment] 2018-01-07 10:01
> and is there any possibility to leave my original file untouched when syncing back to Dropbox?

So you sometimes have an empty line as the last line in the content and sometimes not? What about if you refile a note, should its content keep having that empty line, regardless of (now different) note which is below it?

I'm trying to understand if content (everything until the next heading in Orgzly's terms) could be always kept as it is, *no matter where the note is located*.

If this were to be done, you'd have this:

Starting from:

```
* Note 1
* Note 2
* Note 3

* Note A
* Note B
* Note C
```

If you move Note 3 above Note 2, you'd get:

```
* Note 1
* Note 3

* Note 2
* Note A
* Note B
* Note C
```

In Org mode this would not be the case, but Orgzly is not an editor - that is, it only deals with notes, so line can only be part of a specific note's content.

This is why app is kinda "normalizing" the spacing between notes and you get:

```
* Note 1
* Note 3
* Note 2
* Note A
* Note B
* Note C
```

with "Separate notes with an empty line" set to "Never".

**Comment by nevenz** [comment] 2019-09-27 16:44
Closing as a duplicate of #190.

**Closed by nevenz** 2019-09-27 16:44 UTC
Labels: Type: feature
