### ISSUE TITLE
Allow pre-defined options for adding notes

### ISSUE THREAD

**Issue by rieje** [orgzly/orgzly-android#583] opened 2019-08-12 15:06 UTC
- [ x ] I have searched for existing issues that may be the same as or related to mine.

Similar to pre-defined searches, allow pre-defined adding of notes (e.g. click widget button and a note gets added with pre-defined options, e.g. TODO state of `NEXT`, Priority of A, scheduled 1 hour from now). It makes capturing notes more efficient, e.g. have 4 widget shortcuts each with commonly used options. Currently, the widget only allows creating a note for a specific notebook.

Pressing the widget shortcut should then put the cursor directly on editing the content, so you only need to type out the notes and submit.

**Comment by nevenz** [comment] 2019-08-15 05:34
This is #80 I think, started in #466.

**Comment by nevenz** [comment] 2019-09-27 16:00
I'll close it as a duplicate of #80 (mentioning of voice commands might be misleading in that issue, but it's the main one for implementing templates).

**Closed by nevenz** 2019-09-27 16:00 UTC
Labels: New, Type: feature
