### ISSUE TITLE
How feasible would it be to allow separating notebooks by folders?

### ISSUE THREAD

**Issue by paulorssalves** [orgzly/orgzly-android#681] opened 2020-03-23 15:14 UTC
This is something that is very present in my org workflow. I have many different org files arranged in different folders, because some things are best kept separate. Of course, if we would like to sync our notebooks, it would be best if they were all kept within the syncing folder.

I would like to know if the current status of the code (or the intention behind the project) would make this idea more or less actionable.

**Comment by nevenz** [comment] 2020-04-30 10:11
It's definitely needed. See also #225. I'm not sure if this issue should be closed as a duplicate, or treated as a dependency.

**Comment by nevenz** [comment] 2020-08-24 08:44
Closing as duplicate of #532.

**Closed by nevenz** 2020-08-24 08:44 UTC
Labels: Type: feature
