### ISSUE TITLE
^L (page breaks) are getting removed

### ISSUE THREAD

**Issue by steckerhalter** [orgzly/orgzly-android#261] opened 2018-01-02 09:01 UTC
I was starting to use ^L to separate content. It seems like orgzly is removing them. Quite a trifle but I thought I'll report it anyway 😆

**Comment by nevenz** [comment] 2018-01-03 13:41
Any chance you could attach a sample org file with those? Thanks!

**Comment by steckerhalter** [comment] 2018-01-04 13:04
rename to org: [sample.txt](https://github.com/orgzly/orgzly-android/files/1603388/sample.txt)

**Comment by nevenz** [comment] 2018-01-04 19:04
Ah, so anywhere in the content.

I can't reproduce it, trying Dropbox and directory syncing back and forth, with and without editing the content.

Do you use some other method for syncing through directory repo? What version of Orgzly is that?

**Comment by steckerhalter** [comment] 2018-01-05 09:07
It's version 1.6. I'm auto syncing with a folder and syncthing. I have to check if the problem really occurs with the sample. I was assuming it does but I'm not sure.

**Comment by steckerhalter** [comment] 2018-01-05 09:37
here's the thing, it only seems to get stripped as part of heading, I'm attaching a sample
[sample.txt](https://github.com/orgzly/orgzly-android/files/1606115/sample.txt)

so if I add a new heading in orgzly, the page break vanishes

**Comment by nevenz** [comment] 2018-01-05 10:36
OK, thanks makes sense, because heading is parsed using `\s` in regex, which includes form feed character.

How bad you need this? And I'm curious why? 

We can probably just start using space and tab, but it would have to be tested in a lot of scenarios and might be more work then it's worth it.

**Comment by steckerhalter** [comment] 2018-01-05 11:27
I was using it to separate content. I don't need it badly so nevermind if you don't feel like it's important enough.

**Comment by nevenz** [comment] 2018-01-09 10:38
It looks like it's not just a matter of the main regex, it's probably "cleaned" somewhere else too. I'll give it a closer look and check what Org mode does.

I might close it if it turns out to be too much work.

**Comment by steckerhalter** [comment] 2018-01-09 10:42
Thanks, maybe it's silly anyway to use ^L in a heading?

**Comment by nevenz** [comment] 2018-01-09 10:50
> Thanks, maybe it's silly anyway to use ^L in a heading?

I don't see the reason for it personally, nor I'd know how to. 😄

**Comment by steckerhalter** [comment] 2018-01-09 11:23
Right, thinking about it now it's probably not even proper to do it. Maybe forget about it?

**Comment by nevenz** [comment] 2018-01-09 11:46
Yeah, that would make sense. I'd eventually take a look, but it's not high on my priority list, so it would take a while. You can close the issue, thanks.

**Closed** 2018-01-09 11:58 UTC
Labels: type.improvement
