### ISSUE TITLE
Internal links: how it works?

### ISSUE THREAD

**Issue by srustamo** [orgzly/orgzly-android#243] opened 2017-12-04 13:56 UTC
I have two notebooks `A` and `B`. One entry in `A` has a CUSTOM_ID. A note in `B` refers to note in `A`. A link shows up and clickable in Orgzly, however, it only shows a message that 'Note with "ID" property set to "`hex here`"' and nothing else happens.

I expected the link to be opened and notebook `A` brought to front of the screen with relevant linked heading active.

**Comment by nevenz** [comment] 2017-12-04 14:10
You mention two different properties, perhaps that's the issue?

* `[[id:hex]]` links to note with property `ID` set to `hex`.
* `[[#any text]]` links to note with property `CUSTOM_ID` set to `any text`.

You should probably using `CUSTOM_ID` if you're creating new link targets.

`ID` and its value (which needs to be formatted as [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier)) is there for users who already have those links created by Org mode. You can use it, but it's pain to input the value.

UI for all this is yet to be created (setting properties automatically, then pasting the link), to make things less error-prone and more user-friendly.

**Comment by srustamo** [comment] 2017-12-04 14:16
Sorry for confusion, actually the property in `A` is `ID`, not `CUSTOM_ID`.

I'm not creating any links in Orgzly, but trying to open the linked note. The links are already there, created in Emacs, files then synced to Orgzly via Dropbox sync.

**Comment by nevenz** [comment] 2017-12-04 14:24
Perhaps case is different? I just noticed that it matters, which it shouldn't. It'll be fixed in the next version.

If that's not it either, can you post snippets of two notes and the exact error message?

**Comment by srustamo** [comment] 2017-12-04 14:48
Just created a new test note, everything works as expected. 

However, it looks like if the note, to which a link points from another notebook, has a :LOGBOOK: drawer, the link then stops opening the note and starts showing the message 'Note with "ID" property set to "hex here"'.

**Comment by nevenz** [comment] 2017-12-04 15:05
> However, it looks like if the note, to which a link points from another notebook, has a :LOGBOOK: drawer, the link then stops opening the note and starts showing the message 'Note with "ID" property set to "hex here"'.

Do you see the property set in that note? Perhaps you have PROPERTIES after LOGBOOK, so they are not parsed (you would see them in the note's content and not above "Add property"). I don't see another reason why would LOGBOOK matter.

Can you reproduce this with that new test note you created?

**Comment by srustamo** [comment] 2017-12-04 15:26
> Perhaps you have PROPERTIES after LOGBOOK
This. 

But it seems that it is a standard Org behavior. On a newly created org file heading, <kbd>C-l</kbd> would create a :PROPERTIES: drawer with `ID`, if `org-id-link-to-org-use-id` is set to `create-if-interactive`. 

If then this heading clocked-in and out, a :LOGBOOK: drawer is created before :PROPERTIES: drawer, at least in my config. 

OS X 10.9.5, GNU Emacs 25.3.1 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21) of 2017-10-23

**Comment by srustamo** [comment] 2017-12-04 15:41
>Do you see the property set in that note?

If :LOGBOOK: drawer is present, :PROPERTIES: drawer is not set, but visible as note text. So, you are right, it does not get parsed.

**Comment by nevenz** [comment] 2017-12-04 15:41
> If then this heading clocked-in and out, a :LOGBOOK: drawer is created before :PROPERTIES: drawer, at least in my config.

> OS X 10.9.5, GNU Emacs 25.3.1 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21) of 2017-10-23

What does org-version say? It can't be < 8.3, can it? (I'm using the one from the repo, so I'm not in the loop on emacs vs org-mode versions). 

Anyway, since 8.3, `:PROPERTIES:` are required to be right after heading or planning times. And in Orgzly LOGBOOK is not yet (orgzly/org-java#4) parsed, so it's considered a content and everything after that is too.

**Comment by srustamo** [comment] 2017-12-04 15:44
> It can't be < 8.3

It can :)

I'm using 8.2.9 for compatibility reasons for some other package. Alas.

**Comment by nevenz** [comment] 2017-12-04 15:56
Is `:LOGBOOK`: the only thing above `:PROPERTIES:` you have? orgzly/org-java#4 should help here if so.

**Comment by srustamo** [comment] 2017-12-04 16:01
I think so. There are SCHEDULED and DEADLINE entries above :PROPERTIES:, but these are not drawers.

Thanks for that PR link.

**Closed** 2018-04-10 08:43 UTC
Labels: type.question
