### ISSUE TITLE
Too many org files

### ISSUE THREAD

**Issue by RonnyD123** [orgzly/orgzly-android#344] opened 2018-06-13 03:33 UTC
It seems to be all or nothing in Orgzly. Can I limit which files I sync? Or sort them somehow by repository? I have many, too many for one long list in Orgzly book screen

**Comment by nevenz** [comment] 2018-06-17 13:33
Currently you can only store all files you want to sync in a single directory, then create repository for it.

I'll close this as a duplicate of #273 and #288 though.

**Closed by nevenz** 2018-06-17 13:33 UTC
