### ISSUE TITLE
Backup/restore configuration

### ISSUE THREAD

**Issue by bkhl** [orgzly/orgzly-android#936] opened 2022-05-03 15:17 UTC
Since I use the app on more than one phone, I've found myself needing to manually change a bunch of config to match my preferences. If I make some change, I tend to end up with mismatching config on different phones and getting disorientated.

It would have been handy if there was a way to dump/restore the application config to a file.

**Comment by romariorobby** [comment] 2022-05-12 14:43
Yeah, i do the same. For now, i just backup search queries. but backup whole orgzly config would be helpful.

**Comment by xiaoruoruo** [comment] 2022-07-22 22:44
I think this is dupe of #156

**Closed** 2024-10-06 19:14 UTC
Labels: Type: feature
