### ISSUE TITLE
Multimedia support

### ISSUE THREAD

**Issue by drym3r** [orgzly/orgzly-android#305] opened 2018-03-27 20:05 UTC
I'm submitting a **feature request**.

I'd would be very cool to be able to add voice recordings, videos or photos to notes. Something like [omni notes](https://github.com/federicoiosue/Omni-Notes). 

Thanks for your work!

**Comment by nevenz** [comment] 2018-03-29 11:59
I think this could be considered a duplicate of #1?

**Comment by drym3r** [comment] 2018-03-29 14:55
Yes, I didn't see that one. This issue may be closed, but it may be interesting to have as reference omni notes.

**Comment by nevenz** [comment] 2018-03-29 17:03
> This issue may be closed, but it may be interesting to have as reference omni notes.

Cool, yes, it's linked now.

**Closed by nevenz** 2018-03-29 17:03 UTC
