### ISSUE TITLE
Ways to opt in for Beta testing

### ISSUE THREAD

**Issue by hyiltiz** [orgzly/orgzly-android#234] opened 2017-11-26 07:39 UTC
I installed it from F-Droid recently and am enjoying it. I saw that syncing via a git repository is coming soon, and am excited about it. Is there any way to opt into the Beta stream to test stuff out without having to build it myself? Ideally, an easy way to opt into the beta stream would be ideal for development as well, since you get more frequent feedback, and contributions from users who would like to contribute.

**Comment by nevenz** [comment] 2017-11-26 17:22
Git repo work isn't merged yet, but you can find APKs in #173.

You can join beta for pre-production releases at https://play.google.com/apps/testing/com.orgzly. Currently v1.6.1 is in it (http://www.orgzly.com/changelog#v1.6.1). These are usually just about-to-be-released versions, not what you're asking for.

**Comment by mrvocalplay** [comment] 2017-11-30 07:55
Is there a way to get the pre-production releases on a other way than google play and self buildu? Fore example f-droid?

**Comment by nevenz** [comment] 2017-11-30 09:35
> Is there a way to get the pre-production releases on a other way than google play and self buildu? Fore example f-droid?

All APKs (beta and production) are available on https://github.com/orgzly/orgzly-android/releases

**Comment by hyiltiz** [comment] 2017-11-30 19:51
I can certainly feel @mrvocalplay's concern, but am content at the moment with the Google Play link. Maybe we can put this link in the Wiki?

**Comment by mrvocalplay** [comment] 2017-12-01 09:19
Thanks for the link.. I tried to install the latest apk (beta.2) a couple of times but I always got an App not installed answer...

**Comment by nevenz** [comment] 2017-12-01 09:46
> Google Play link. Maybe we can put this link in the Wiki?

I'll see to mention it in [README.org](https://github.com/orgzly/orgzly-android/blob/master/README.org).

> I tried to install the latest apk (beta.2) a couple of times but I always got an App not installed answer

Hmm weird. When? When you try to run it? But it gets installed (or looks like it)?

What about if you try https://f-droid.org/repo/com.orgzly_83.apk the same way?

What Android version is that?

**Comment by mrvocalplay** [comment] 2017-12-01 18:02
I tried it last night and today morning. Every time downloaded it new. The last apk you linked works just fine.

Am am still on Android 6.0.1 with CM13.

**Comment by nevenz** [comment] 2017-12-02 18:04
I meant at point does it give you "App not installed" message, installation, or when you try to run it.

But never mind, I just managed to reproduce it - it happens when you already have F-Droid version installed (as it's not signed with the same key).

So just uninstall the existing app first.

**Comment by mrvocalplay** [comment] 2017-12-03 11:38
Oh okay... I misunderstood this.. I get an " App not installed" message. But thanks.. I try to uninstall the f-droid one and then the new one.

**Closed** 2019-09-27 16:43 UTC
Labels: Type: question
